Last review : 2017 October 20th

* Integration (emacs nu 1)

Now that emacs-nu starts to be mature, the most lacking features becomes to be : integration with other modes. Other completiosn like ido, snippets should be integrated, Project management, and more. Some hydra might appear, or not.

The current code refactoring will help making clear what is, or not, available in emacs-nu. Of course everything is available, but not necessarily integrated. Integration mechanism might evolve, too, if useful, like adding some defmacros to emacs-nu.

* Immediate Keys & Ergonomy / Dvorak (emacs nu 2)

The control keys, & the "do-prompt" main entry point, should remain associated with letters as in modern conventions. But the alt keys are thought for ergonomy. As of today, menu-associated keys use the Alt for an immediate function regarding this same menu. But this does not make sense for Dvorak or other layouts. Also, even for Azerty/Qwerty, while this is rather ergonomic because of the navigation paddle & the do-prompt, is not based on statistics like ErgoEmacs. It might be possible to have best of both worlds, but this requires first integration to be more completion & emacs nu a little more mature. 
